---
- name: Configure www-data user for SSH access
  hosts: all
  become: yes
  tasks:
    - name: Install Git
      ansible.builtin.apt:
        name: git
        state: present

    - name: Ensure the /var/www/tmp directory exists
      file:
        path: /var/www/tmp
        state: directory
        mode: "0755"
        owner: www-data
        group: www-data

    - name: Change login shell for 'www-data' to '/bin/bash'
      user:
        name: www-data
        shell: /bin/bash

    - name: Assign home directory to 'www-data'
      user:
        name: www-data
        home: /var/www
        move_home: yes

    - name: Create .ssh directory with correct ownership and permissions
      file:
        path: /var/www/.ssh
        state: directory
        owner: www-data
        group: www-data
        mode: "0700"

    - name: Remove existing SSH files from /var/www/.ssh
      become: yes
      become_user: root
      ansible.builtin.shell: |
        find /var/www/.ssh -type f -exec rm -v {} \;
      args:
        warn: false
      when: ansible_user == 'debian'
      ignore_errors: yes

    - name: Copy provided SSH private key for 'www-data'
      copy:
        src: "{{ www_data_private_key_path }}"
        dest: /var/www/.ssh/id_rsa
        owner: www-data
        group: www-data
        mode: "0600"

    - name: Copy provided SSH public key for 'www-data'
      copy:
        src: "{{ www_data_public_key_path }}"
        dest: /var/www/.ssh/id_rsa.pub
        owner: www-data
        group: www-data
        mode: "0600"

    - name: Load public key from local file
      set_fact:
        public_key_content: "{{ lookup('file', www_data_public_key_path) }}"

    - name: Ensure authorized_keys exists and contains the public key
      lineinfile:
        path: "/var/www/.ssh/authorized_keys"
        line: "{{ public_key_content }}"
        create: yes
        owner: www-data
        group: www-data
        mode: "0600"

    - name: Ensure VSCode can write to /var/www/
      file:
        path: /var/www/
        state: directory
        owner: www-data
        group: www-data
        recurse: yes

    - name: Ensure .org directory exists in ~/.ssh/
      file:
        path: /var/www/.ssh/.{{ org }}/
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: "0700"

    - name: Ensure the SSH directory exists
      file:
        path: "/home/debian/.ssh/.{{ org }}"
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: "0700"

    - name: Ensure debian owns the ~/.ssh/.<<org>>/ directory
      become: yes # This will escalate privileges
      become_user: root # This specifies which user to become, if different from default
      file:
        path: "/home/debian/.ssh/.{{ org }}/"
        state: directory
        owner: debian
        group: debian
        recurse: yes
